name: copy pdfs to web branch

on:
  workflow_dispatch:
  push:
    branches:
      - build
    paths:
      - "**.pdf"

jobs:
  copy:
    name: Copy PDFs to web branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.email "gabriel_ong@ieee.org"
          git config user.name "Gabriel Ong"

      - name: Create or switch to web branch
        run: |
          if git ls-remote --exit-code --heads origin web; then
            git checkout -B web origin/web
          else
            git checkout --orphan web
            git rm -rf .
            echo "<!DOCTYPE html><html><body><h1>Coming Soon</h1></body></html>" > index.html
            git add index.html
            git commit -m "Initialize web branch"
            git push origin web
          fi

      - name: Clean existing files
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          git add -A
          git commit -m "Clean old files" || echo "Nothing to clean"

      - name: Fetch all PDFs from build branch
        run: |
          git fetch origin build
          mkdir -p temp
          git --work-tree=temp checkout origin/build -- .
          find temp -name "*.pdf" -exec cp --parents {} . \;
          rm -rf temp

      - name: Commit and push updated PDFs
        run: |
          git add .
          git commit -m "Update PDFs from build branch" || echo "No changes to commit"
          git push origin web